import{initializeTheme}from'./theme.js';
import{search,saveRecent,renderPicks}from'./search.js';
import{analyze,storyMarkup}from'./story.js';
import{downloadCard,copyProfile,shareProfile}from'./export.js';
import{observeReveals}from'./utils.js';
initializeTheme();observeReveals();
const form=document.querySelector('#search-form');const input=document.querySelector('#username');const button=document.querySelector('#submit-button');const status=document.querySelector('#status');const picks=document.querySelector('#quick-picks');const story=document.querySelector('#story');let current=null;let activeObserver=null;
function showPicks(){renderPicks(picks,name=>{input.value=name;run(name)})}
async function run(name){button.disabled=true;status.className='status';status.textContent='Preparing your story…';picks.hidden=true;try{const data=await search(name,status);const analysis=analyze(data);current={data,analysis};saveRecent(data.profile.login);story.innerHTML=storyMarkup(data,analysis);story.hidden=false;document.querySelector('#how').hidden=true;status.textContent='';const url=new URL(location.href);url.searchParams.set('u',data.profile.login);history.replaceState({},'',url);bindStoryActions();observeReveals(story);setTimeout(()=>story.scrollIntoView({behavior:'smooth'}),100)}catch(error){status.className='status error';status.textContent=error.message;picks.hidden=false}finally{button.disabled=false;showPicks()}}
function initializeTilt(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;story.querySelectorAll('.tilt-card').forEach(card=>{card.addEventListener('pointermove',event=>{const box=card.getBoundingClientRect();const x=(event.clientX-box.left)/box.width;const y=(event.clientY-box.top)/box.height;card.style.setProperty('--tilt-x',`${(0.5-y)*7}deg`);card.style.setProperty('--tilt-y',`${(x-0.5)*7}deg`);card.style.setProperty('--shine-x',`${x*100}%`);card.style.setProperty('--shine-y',`${y*100}%`)});card.addEventListener('pointerleave',()=>{card.style.setProperty('--tilt-x','0deg');card.style.setProperty('--tilt-y','0deg')})})}
function animateNumbers(){if(activeObserver){activeObserver.disconnect();activeObserver=null}const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const format=(value,element)=>element.dataset.compact==='true'?new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(value):Math.round(value)+String(element.dataset.suffix||'');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const scope=entry.target;scope.querySelectorAll('.count-up').forEach(element=>{const target=Number(element.dataset.count||0);if(reduced){element.textContent=format(target,element);return}const started=performance.now();const tick=now=>{const progress=Math.min(1,(now-started)/1100);const eased=1-Math.pow(1-progress,4);element.textContent=format(target*eased,element);if(progress<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)});scope.querySelectorAll('.animated-bar').forEach(bar=>bar.classList.add('is-animated'));observer.unobserve(scope)}),{threshold:.22});activeObserver=observer;story.querySelectorAll('.story-section').forEach(section=>observer.observe(section))}
function bindStoryActions(){const downloadBtn=story.querySelector('[data-action="download"]');const copyBtn=story.querySelector('[data-action="copy"]');const shareBtn=story.querySelector('[data-action="share"]');if(downloadBtn)downloadBtn.addEventListener('click',()=>downloadCard(current.data,current.analysis));if(copyBtn)copyBtn.addEventListener('click',()=>copyProfile(current.data.profile.login));if(shareBtn)shareBtn.addEventListener('click',()=>shareProfile(current.data.profile.login));initializeTilt();animateNumbers()}
form.addEventListener('submit',event=>{event.preventDefault();run(input.value)});showPicks();const deepLink=new URLSearchParams(location.search).get('u');if(deepLink){input.value=deepLink;run(deepLink)}
addEventListener('scroll',()=>{const available=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--scroll',`${available?scrollY/available*100:0}%`)},{passive:true});
